language: go

go:
- 1.13.x

install:
- go install github.com/onsi/ginkgo/ginkgo
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.36.0

script:
- golangci-lint run
- ginkgo -r -randomizeSuites -randomizeAllSpecs -keepGoing -race -cover -trace
